create table public.favoritos (
  id bigint generated by default as identity not null,
  id_cuenta uuid not null,
  id_recurso bigint not null,
  created_at timestamp with time zone not null default now(),
  constraint favoritos_pkey primary key (id),
  constraint favoritos_unique unique (id_cuenta, id_recurso),
  constraint favoritos_id_cuenta_fkey foreign key (id_cuenta) references cuentas (id) on delete cascade,
  constraint favoritos_id_recurso_fkey foreign key (id_recurso) references recursos (id) on delete cascade
) TABLESPACE pg_default;

alter table public.favoritos enable row level security;

create policy "Ver mis favoritos"
on public.favoritos for select
using (auth.uid() = id_cuenta);

create policy "Insertar mis favoritos"
on public.favoritos for insert
with check (auth.uid() = id_cuenta);

create policy "Eliminar mis favoritos"
on public.favoritos for delete
using (auth.uid() = id_cuenta);