create table public.recursos (
  id bigint generated by default as identity not null,
  name character varying null,
  description text null,
  category character varying null,
  type character varying null,
  path text null,
  image_preview text null,
  created_at timestamp with time zone not null default now(),
  id_cuenta uuid null default gen_random_uuid (),
  constraint recursos_pkey primary key (id),
  constraint recursos_id_cuenta_fkey foreign KEY (id_cuenta) references cuentas (id) on update CASCADE on delete set null
) TABLESPACE pg_default;


